<a href="https://colab.research.google.com/github/Ravikumarchavva/Ravi-kumar-svce/blob/main/Copy_of_num.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                                            **NUMPY**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

*reshape(rows,coloums)*

In [ ]:
a.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

*arange(start,stop,step)*

In [ ]:
b=np.arange(1,10,step=1).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
a**b

array([[        1,         4,        27],
       [      256,      3125,     46656],
       [   823543,  16777216, 387420489]])

In [ ]:
import copy as cp
c=cp.copy(a)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
d=cp.deepcopy(b)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])